{"uuid": "41787cd5-d2ee-474a-8037-ead26736bd02", "start": 1562387009295, "status": "passed", "fullName": "TestCases.test_login_pytest.TestLoginP#test_login_0_failed_by_wrong_datas[data3]", "name": "test_login_0_failed_by_wrong_datas[data3]", "stop": 1562387010259, "historyId": "8c297d3530a4b2fa8edc344d628138ad", "parameters": [{"name": "data", "value": "{'user': '1868472055', 'check': '请输入正确的手机号', 'password': 'python'}"}], "labels": [{"name": "tag", "value": "login"}, {"name": "suite", "value": "test_login_pytest"}, {"name": "parentSuite", "value": "TestCases"}, {"name": "subSuite", "value": "TestLoginP"}, {"name": "host", "value": "G50-75M"}, {"name": "thread", "value": "17676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test_login_pytest"}]}